### ISSUE TITLE
AttributeError: object has no attribute 'id' 

### ISSUE THREAD

**Issue by hasanbarary** [maubot/rss#16]
Error while polling feeds
23:17:26	ERROR	instance.rss	Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feedparser.py", line 398, in __getattr__
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/plugins/xyz.maubot.rss-v0.1.0.mbp/rss/bot.py", line 111, in _poll_feeds
    await self._poll_once()
  File "/data/plugins/xyz.maubot.rss-v0.1.0.mbp/rss/bot.py", line 100, in _poll_once
    new_entries = {entry.id: entry for entry in self.find_entries(feed.id, entries)}
  File "/data/plugins/xyz.maubot.rss-v0.1.0.mbp/rss/bot.py", line 147, in find_entries
    return [Entry(
  File "/data/plugins/xyz.maubot.rss-v0.1.0.mbp/rss/bot.py", line 149, in <listcomp>
    id=entry.id,
  File "/usr/lib/python3.8/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'id'

**Comment by tulir** [comment]
Already fixed, use the master branch (e.g. from the [CI](https://mau.dev/maubot/rss/pipelines))
