### ISSUE TITLE
Cannot import name 'Scheme' from 'mautrix.util.async_db'

### ISSUE THREAD

**Issue by floviolleau** [maubot/rss#34]
Hi,

I just discovered maubot and it seems amazing.

I have some issue. I tried echo, it didn't work. When I type `!echo test` in a chat with the bot, nothing happens and nothing in logs

I wanted to try rss bot but I face to this issue:

<details>
  <summary>Click to expand and see logs</summary>

```  
[2022-06-16 01:31:21,886] [INFO@mau.init] Initializing maubot 0.2.0
[2022-06-16 01:31:21,892] [DEBUG@maubot.instance.zip] Preloading plugins...
[2022-06-16 01:31:21,928] [DEBUG@maubot.instance.zip] Preloaded plugin xyz.maubot.echo from /home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.echo-v1.4.0.mbp
[2022-06-16 01:31:21,962] [DEBUG@maubot.instance.zip] Preloaded plugin xyz.maubot.rss from /home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp
[2022-06-16 01:31:22,211] [DEBUG@maubot.instance.botinstance] Plugin instance dependencies loaded
[2022-06-16 01:31:22,238] [DEBUG@maubot.instance.botrssinstance] Plugin instance dependencies loaded
[2022-06-16 01:31:22,240] [INFO@mau.init] Initialization complete in 0.77 seconds
[2022-06-16 01:31:22,241] [DEBUG@mau.init] Running startup actions...
[2022-06-16 01:31:22,318] [DEBUG@maubot.client.@buddybot:myserver.zapto.org] Starting syncing
[2022-06-16 01:31:22,342] [INFO@maubot.client.@buddybot:myserver.zapto.org] Client started, starting plugin instances...
[2022-06-16 01:31:22,391] [DEBUG@maubot.instance.zip] Loaded and imported plugin xyz.maubot.echo from /home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.echo-v1.4.0.mbp
[2022-06-16 01:31:22,394] [INFO@maubot.instance.botinstance] Started instance of xyz.maubot.echo v1.4.0 with user @buddybot:myserver.zapto.org
[2022-06-16 01:31:22,728] [ERROR@maubot.instance.zip] Failed to load xyz.maubot.rss v0.3.1
Traceback (most recent call last):
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 203, in _load
    importer.load_module(module)
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/__init__.py", line 1, in <module>
    from .bot import RSSBot
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/bot.py", line 42, in <module>
    from .db import DBManager, Entry, Feed, Subscription
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/db.py", line 26, in <module>
    from mautrix.util.async_db import Database, Scheme
ImportError: cannot import name 'Scheme' from 'mautrix.util.async_db' (/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/mautrix/util/async_db/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 188, in load
    return self._load(reset_cache)
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 207, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module rss
[2022-06-16 01:31:22,745] [ERROR@maubot.client.@buddybot:myserver.zapto.org] Failed to start
Traceback (most recent call last):
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 203, in _load
    importer.load_module(module)
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/lib/zipimport.py", line 282, in load_module
    exec(code, mod.__dict__)
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/__init__.py", line 1, in <module>
    from .bot import RSSBot
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/bot.py", line 42, in <module>
    from .db import DBManager, Entry, Feed, Subscription
  File "/home/user/projects/matrix/bots/maubot/plugins/xyz.maubot.rss-v0.3.1.mbp/rss/db.py", line 26, in <module>
    from mautrix.util.async_db import Database, Scheme
ImportError: cannot import name 'Scheme' from 'mautrix.util.async_db' (/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/mautrix/util/async_db/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/client.py", line 130, in start
    await self._start(try_n)
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/client.py", line 203, in _start
    await self.start_plugins()
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/client.py", line 206, in start_plugins
    await asyncio.gather(*[plugin.start() for plugin in self.references])
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/instance.py", line 173, in start
    cls = await self.loader.load()
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 188, in load
    return self._load(reset_cache)
  File "/home/user/projects/matrix/bots/maubot/lib/python3.7/site-packages/maubot/loader/zip.py", line 207, in _load
    raise MaubotZipLoadError(f"Failed to load module {module}")
maubot.loader.zip.MaubotZipLoadError: Failed to load module rss
[2022-06-16 01:31:22,755] [INFO@maubot.server] Listening on http://0.0.0.0:29316
[2022-06-16 01:31:22,757] [INFO@mau.init] Startup actions complete in 0.52 seconds, now running forever
```
</details>

<details>
  <summary>Click to expand ans see pip list in vhost of maubot</summary>
  
```
Package             Version
------------------- -------
aiohttp             3.8.1
aiosignal           1.2.0
alembic             1.8.0
async-timeout       4.0.2
asyncpg             0.25.0
asynctest           0.13.0
attrs               21.4.0
bcrypt              3.2.2
cffi                1.15.0
charset-normalizer  2.0.12
click               7.1.2
colorama            0.4.4
commonmark          0.9.1
feedparser          6.0.10
frozenlist          1.3.0
idna                3.3
importlib-metadata  4.11.4
importlib-resources 5.7.1
Jinja2              3.1.2
Mako                1.2.0
MarkupSafe          2.1.1
maubot              0.2.0
mautrix             0.14.10
multidict           6.0.2
packaging           21.3
pip                 22.1.2
prompt-toolkit      3.0.29
psycopg2            2.9.3
pycparser           2.21
pyparsing           3.0.9
questionary         1.10.0
ruamel.yaml         0.17.21
ruamel.yaml.clib    0.2.6
setuptools          57.0.0
sgmllib3k           1.0.0
SQLAlchemy          1.3.24
typing_extensions   4.2.0
wcwidth             0.2.5
wheel               0.37.0
yarl                1.7.2
zipp                3.8.0
```
</details>

What can I do?

**Comment by tulir** [comment]
Don't use outdated versions of maubot
